import OpenAI from "openai";
import type { GenerateStoryRequest, GenerateStoryResponse, StoryDiagnostics } from "./types";
import { normalizeStoryPayload, normalizeStoryText, normalizeStringList } from "./story-output";
import {
  countWords,
  inferCharactersUsed,
  inferRulesReferenced
} from "./story-analysis";

type OpenAIStoryPayload = {
  story: string;
  charactersUsed?: string[];
  rulesReferenced?: string[];
};

const DEFAULT_MODEL = "gpt-4.1-mini";

export function hasOpenAIKey(): boolean {
  return Boolean(process.env.OPENAI_API_KEY?.trim());
}

export function getOpenAIModel(): string {
  return process.env.OPENAI_MODEL?.trim() || DEFAULT_MODEL;
}

export function getOpenAIDiagnostics(overrides: Partial<StoryDiagnostics> = {}): StoryDiagnostics {
  const apiKeyDetected = hasOpenAIKey();

  return {
    openAIEnabled: apiKeyDetected,
    apiKeyDetected,
    modelRequested: getOpenAIModel(),
    openAIRequestAttempted: false,
    openAIRequestSucceeded: false,
    fallbackReason: null,
    ...overrides
  };
}

export async function generateOpenAIStory(input: GenerateStoryRequest): Promise<GenerateStoryResponse> {
  const client = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY
  });

  const response = await client.chat.completions.create({
    model: getOpenAIModel(),
    temperature: 0.8,
    max_tokens: 4500,
    response_format: { type: "json_object" },
    messages: [
      {
        role: "system",
        content:
          "You are a literary short story engine for creators. Write original fiction only. Use creator-provided sections as source material, not as text to copy. Preserve world rules, character consistency, story request, and narrative constraints. Narrative rules take priority over generic literary defaults. Do not mention AI, prompts, models, source files, section labels, or generation. Return only valid JSON matching this shape: {\"story\":\"...\",\"charactersUsed\":[\"...\"],\"rulesReferenced\":[\"...\"]}."
      },
      {
        role: "user",
        content: buildPrompt(input)
      }
    ]
  });

  const payload = parseStoryPayload(response.choices[0]?.message.content ?? "");
  const story = normalizeStoryText(payload.story);

  if (!story) {
    throw new Error("OpenAI response did not include a story.");
  }

  const ruleSources = `${input.worldBible}\n\n${input.storyRules}`;

  return {
    story,
    metadata: {
      wordCount: countWords(story),
      charactersUsed: normalizeList(payload.charactersUsed, inferCharactersUsed(story, input.characterProfiles)),
      rulesReferenced: normalizeList(payload.rulesReferenced, inferRulesReferenced(story, ruleSources)),
      source: "openai",
      diagnostics: getOpenAIDiagnostics({
        openAIRequestAttempted: true,
        openAIRequestSucceeded: true
      })
    }
  };
}

function buildPrompt(input: GenerateStoryRequest): string {
  return `Write a 1500-2000 word literary short story using only this creator-supplied source material.

Generation requirements:
- Use the four internal sections below as source material only.
- Preserve world rules from WORLD BIBLE.
- Preserve character consistency from CHARACTERS.
- Build the story around STORY REQUEST.
- Let NARRATIVE RULES guide generation and take priority over generic literary defaults.
- Do not reproduce section labels, prompt text, bullet lists, or file contents verbatim.
- Do not mention that the story was generated by AI or based on uploaded files.
- Return metadata for characters used and rules referenced.

WORLD BIBLE
${input.worldBible}

CHARACTERS
${input.characterProfiles}

STORY REQUEST
${input.storySeed}

NARRATIVE RULES
${input.storyRules}`;
}

function parseStoryPayload(rawText: string): OpenAIStoryPayload {
  const payload = normalizeStoryPayload(rawText);
  const story = normalizeStoryText(payload.story ?? rawText);

  return {
    story,
    charactersUsed: normalizeStringList(payload.charactersUsed),
    rulesReferenced: normalizeStringList(payload.rulesReferenced)
  };
}

function normalizeList(values: string[] | undefined, fallback: string[]): string[] {
  const source = values && values.length > 0 ? values : fallback;
  return [...new Set(source.map((value) => value.trim()).filter(Boolean))].slice(0, 10);
}
