import OpenAI from "openai";
import type { GenerateStoryRequest, GenerateStoryResponse, StoryDiagnostics } from "./types";
import {
  countWords,
  inferCharactersUsed,
  inferRulesReferenced
} from "./story-analysis";

type OpenAIStoryPayload = {
  story: string;
  charactersUsed?: string[];
  rulesReferenced?: string[];
};

const DEFAULT_MODEL = "gpt-4.1-mini";

export function hasOpenAIKey(): boolean {
  return Boolean(process.env.OPENAI_API_KEY?.trim());
}

export function getOpenAIModel(): string {
  return process.env.OPENAI_MODEL?.trim() || DEFAULT_MODEL;
}

export function getOpenAIDiagnostics(overrides: Partial<StoryDiagnostics> = {}): StoryDiagnostics {
  const apiKeyDetected = hasOpenAIKey();

  return {
    openAIEnabled: apiKeyDetected,
    apiKeyDetected,
    modelUsed: getOpenAIModel(),
    openAIRequestAttempted: false,
    openAIRequestSucceeded: false,
    fallbackReason: null,
    ...overrides
  };
}

export async function generateOpenAIStory(input: GenerateStoryRequest): Promise<GenerateStoryResponse> {
  const client = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY
  });

  const response = await client.chat.completions.create({
    model: getOpenAIModel(),
    temperature: 0.8,
    max_tokens: 4500,
    response_format: { type: "json_object" },
    messages: [
      {
        role: "system",
        content:
          "You are a literary short story engine for creators. Write original fiction only. Preserve the provided world rules, character consistency, tone, and story seed. Do not mention AI, prompts, models, or generation. Return only valid JSON matching this shape: {\"story\":\"...\",\"charactersUsed\":[\"...\"],\"rulesReferenced\":[\"...\"]}."
      },
      {
        role: "user",
        content: buildPrompt(input)
      }
    ]
  });

  const payload = parseStoryPayload(response.choices[0]?.message.content ?? "");
  const story = payload.story.trim();

  if (!story) {
    throw new Error("OpenAI response did not include a story.");
  }

  return {
    story,
    metadata: {
      wordCount: countWords(story),
      charactersUsed: normalizeList(payload.charactersUsed, inferCharactersUsed(story, input.characterProfiles)),
      rulesReferenced: normalizeList(payload.rulesReferenced, inferRulesReferenced(story, input.worldBible)),
      source: "openai",
      diagnostics: getOpenAIDiagnostics({
        openAIRequestAttempted: true,
        openAIRequestSucceeded: true
      })
    }
  };
}

function buildPrompt(input: GenerateStoryRequest): string {
  return `Write a 1500-2000 word literary short story using this creator-supplied context.

Requirements:
- Preserve world rules from the world bible.
- Preserve character consistency from the character profiles.
- Honor the tone implied by the world bible and profiles.
- Build the story around the story seed.
- Do not mention that the story was generated by AI.
- Return metadata for characters used and rules referenced.

World Bible:
${input.worldBible}

Character Profiles:
${input.characterProfiles}

Story Seed:
${input.storySeed}`;
}

function parseStoryPayload(rawText: string): OpenAIStoryPayload {
  const cleaned = rawText.trim().replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/i, "");

  try {
    return JSON.parse(cleaned) as OpenAIStoryPayload;
  } catch {
    const storyMatch = cleaned.match(/"story"\s*:\s*"([\s\S]*)"\s*,\s*"charactersUsed"/);
    if (storyMatch?.[1]) {
      return {
        story: storyMatch[1].replace(/\\"/g, "\"").replace(/\\n/g, "\n")
      };
    }

    return {
      story: cleaned
    };
  }
}

function normalizeList(values: string[] | undefined, fallback: string[]): string[] {
  const source = values && values.length > 0 ? values : fallback;
  return [...new Set(source.map((value) => value.trim()).filter(Boolean))].slice(0, 10);
}
